name: Code check, unit test and fix dependencies

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install make
        shell: pwsh
        run: choco install make

      - name: Install Poetry 1.8.5
        shell: pwsh
        run: |
          curl -sSL https://install.python-poetry.org | python - --version 1.8.5
          echo "$env:APPDATA\Python\Scripts" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Verify Poetry
        shell: pwsh
        run: poetry --version

      - name: Install dependencies with Poetry
        shell: pwsh
        run: |
          poetry install --no-interaction --no-root

      - name: Run codebase check
        run: make check

      - name: Run unit tests
        run: make test
